appName: gtool
port: 9092

logConfig:
  folder: ./logs/
  filename: app.log
  maxage: 24
  level: info
  maxbackups: 7
  localtime: true
  compress: true
  maxsize: 1

dbConfig:
  dbType: sqlite
  dsn: gtool.db
  skipTransaction: true