appName = "go-web-api"
port = 9092
stack = false

[feature]
disablePProf = true
disableSwagger = false
panicNotify = true
recordMetrics = true
enableCors = true
enableRate = false

[logger]
folder = "./logs/"
filename = "app.log"
maxage = 24
level = "info"
maxbackups = 7
localtime = true
compress = true
maxsize = 1

[database]
dbType = "mysql"
dsn = "127.0.0.1:3306"
dbName = "go_web_api"
skipTransaction = true
username = "root"
password = "root"
connmaxlifetime = 60
maxidleconn = 60
maxopenconn = 10

[cors]
allowedOrigins = "*"
allowedMethods = "GET,POST,HEAD,PUT,PATCH,DELETE"
AllowedHeaders = "*"
AllowCredentials = true

[redis]
addr = "127.0.0.1:6379"
db = "0"
maxretries = 3
minidleconns = 5
pass = ""
poolsize = 10