appName: gtool
port: 9092

logConfig:
  folder: ./logs/
  filename: app.log
  maxage: 24
  level: info
  maxbackups: 7
  localtime: true
  compress: true
  maxsize: 1

dbConfig:
  dbType: mysql
  dsn: root:@tcp(127.0.0.1:3306)/gtool?charset=utf8mb4&parseTime=True&loc=Local
  skipTransaction: true